#!/usr/bin/env node

/**
 * mindlore backup — Git-based backup for ~/.mindlore/
 *
 * Usage:
 *   mindlore backup init         — Create .gitignore, initial commit
 *   mindlore backup github       — Create private GitHub repo + auto-setup
 *   mindlore backup status       — Show git status + last commit
 *   mindlore backup remote <url> — Set remote origin
 *   mindlore backup now          — Manual commit + push
 */

import fs from 'fs';
import path from 'path';
import { execSync, execFileSync } from 'child_process';
import { GLOBAL_MINDLORE_DIR, log } from './lib/constants.js';

const BASE_DIR = GLOBAL_MINDLORE_DIR;
const GIT_DIR = path.join(BASE_DIR, '.git');

// System files that are regenerated by init — shared definition for gitignore and export filtering
const SYSTEM_FILES = ['config.json', 'SCHEMA.md', '.version', '.pkg-version'];

const GITIGNORE_CONTENT = `# WAL files — transient
*.db-shm
*.db-wal

# System files — regenerated by init
${SYSTEM_FILES.join('\n')}

# Cache / temp
diary/_*.json
`;

function backupInit(): void {

  if (!fs.existsSync(BASE_DIR)) {
    console.error('  ~/.mindlore/ not found. Run: npx mindlore init');
    process.exit(1);
  }

  // Create .gitignore
  const gitignorePath = path.join(BASE_DIR, '.gitignore');
  fs.writeFileSync(gitignorePath, GITIGNORE_CONTENT, 'utf8');
  log('Created .gitignore');

  // Init git if needed
  if (!fs.existsSync(GIT_DIR)) {
    execSync('git init', { cwd: BASE_DIR, stdio: 'pipe', timeout: 10000 });
    log('Initialized git repo');
  } else {
    log('Git repo already initialized');
  }

  // Initial commit
  try {
    execSync('git add -A', { cwd: BASE_DIR, stdio: 'pipe', timeout: 10000 });
    const status = execSync('git status --porcelain', {
      cwd: BASE_DIR,
      encoding: 'utf8',
      timeout: 5000,
    }).trim();
    if (status) {
      execSync('git commit -m "mindlore backup init"', {
        cwd: BASE_DIR,
        stdio: 'pipe',
        timeout: 10000,
      });
      log('Initial commit created');
    } else {
      log('Nothing to commit');
    }
  } catch (_err) {
    log('WARNING: Could not create initial commit');
  }
}

function backupStatus(): void {

  if (!fs.existsSync(GIT_DIR)) {
    console.log('  Backup not initialized. Run: mindlore backup init');
    return;
  }

  try {
    const lastCommit = execSync('git log --oneline -1', {
      cwd: BASE_DIR,
      encoding: 'utf8',
      timeout: 5000,
    }).trim();
    log(`Last commit: ${lastCommit}`);
  } catch (_err) {
    log('No commits yet');
  }

  try {
    const remote = execSync('git remote get-url origin', {
      cwd: BASE_DIR,
      encoding: 'utf8',
      timeout: 5000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    log(`Remote: ${remote}`);
  } catch (_err) {
    log('Remote: not configured');
  }

  try {
    const status = execSync('git status --short', {
      cwd: BASE_DIR,
      encoding: 'utf8',
      timeout: 5000,
    }).trim();
    if (status) {
      const lines = status.split('\n');
      log(`Uncommitted: ${lines.length} file(s)`);
    } else {
      log('Working tree clean');
    }
  } catch (_err) {
    log('Could not get status');
  }
}

function backupRemote(url: string): void {

  if (!fs.existsSync(GIT_DIR)) {
    console.error('  Backup not initialized. Run: mindlore backup init');
    process.exit(1);
  }

  try {
    try {
      execSync('git remote get-url origin', {
        cwd: BASE_DIR,
        stdio: 'pipe',
        timeout: 5000,
      });
      execFileSync('git', ['remote', 'set-url', 'origin', url], {
        cwd: BASE_DIR,
        stdio: 'pipe',
        timeout: 5000,
      });
      log(`Remote updated: ${url}`);
    } catch (_err) {
      execFileSync('git', ['remote', 'add', 'origin', url], {
        cwd: BASE_DIR,
        stdio: 'pipe',
        timeout: 5000,
      });
      log(`Remote added: ${url}`);
    }
  } catch (_err) {
    log('WARNING: Could not set remote');
  }
}

/** Stage all, commit if dirty. Returns true if a commit was created. */
function commitIfDirty(message: string): boolean {
  execSync('git add -A', { cwd: BASE_DIR, stdio: 'pipe', timeout: 10000 });
  const status = execSync('git status --porcelain', {
    cwd: BASE_DIR,
    encoding: 'utf8',
    timeout: 5000,
  }).trim();

  if (!status) return false;

  execSync(`git commit -m "${message}"`, {
    cwd: BASE_DIR,
    stdio: 'pipe',
    timeout: 10000,
  });
  return true;
}

/** Push to remote if configured. Returns true if pushed. */
function pushIfRemote(): boolean {
  try {
    execSync('git remote get-url origin', {
      cwd: BASE_DIR,
      stdio: 'pipe',
      timeout: 5000,
    });
    execSync('git push', { cwd: BASE_DIR, stdio: 'pipe', timeout: 15000 });
    return true;
  } catch (_err) {
    return false;
  }
}

function backupNow(): void {

  if (!fs.existsSync(GIT_DIR)) {
    console.error('  Backup not initialized. Run: mindlore backup init');
    process.exit(1);
  }

  try {
    if (!commitIfDirty(`mindlore backup ${new Date().toISOString().slice(0, 19)}`)) {
      log('Nothing to commit — working tree clean');
      return;
    }
    log('Committed');

    if (pushIfRemote()) {
      log('Pushed to remote');
    } else {
      log('No remote configured — local commit only');
    }
  } catch (_err) {
    log('WARNING: Backup failed');
  }
}

function ensureGhAuth(): string {
  try {
    execSync('gh auth status', { stdio: 'pipe', timeout: 10000 });
  } catch (_err) {
    console.error('  GitHub CLI not found or not logged in. Install: https://cli.github.com, then: gh auth login');
    process.exit(1);
  }

  try {
    return execSync('gh api user --jq .login', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      timeout: 10000,
    }).trim();
  } catch (_err) {
    console.error('  Could not get GitHub username');
    process.exit(1);
    return ''; // unreachable but satisfies TS
  }
}

function backupGithub(): void {
  if (!fs.existsSync(BASE_DIR)) {
    console.error('  ~/.mindlore/ not found. Run: npx mindlore init');
    process.exit(1);
  }

  const username = ensureGhAuth();
  const repoName = 'mindlore-data';
  const repoFull = `${username}/${repoName}`;

  // Ensure repo exists
  try {
    execSync(`gh repo view ${repoFull}`, { stdio: 'pipe', timeout: 10000 });
    log(`Repo already exists: ${repoFull}`);
  } catch (_err) {
    try {
      execSync(`gh repo create ${repoFull} --private --description "Mindlore knowledge base backup (auto-synced)"`, {
        stdio: 'pipe',
        timeout: 15000,
      });
      log(`Created private repo: ${repoFull}`);
    } catch (_createErr) {
      console.error('  Could not create repo. Check gh auth permissions.');
      process.exit(1);
    }
  }

  // Ensure git init + gitignore
  if (!fs.existsSync(GIT_DIR)) {
    execSync('git init', { cwd: BASE_DIR, stdio: 'pipe', timeout: 10000 });
    log('Initialized git repo');
  }
  fs.writeFileSync(path.join(BASE_DIR, '.gitignore'), GITIGNORE_CONTENT, 'utf8');
  log('Updated .gitignore');

  // Set remote
  backupRemote(`https://github.com/${repoFull}.git`);

  // Commit + push
  try {
    commitIfDirty('mindlore backup github setup');
    // Only branch -M if there are commits (empty repo has no branch to rename)
    try {
      execSync('git rev-parse HEAD', { cwd: BASE_DIR, stdio: 'pipe', timeout: 5000 });
      execSync('git branch -M main', { cwd: BASE_DIR, stdio: 'pipe', timeout: 5000 });
    } catch (_err) {
      // No commits yet — skip branch rename
    }
    execSync('git push -u origin main', { cwd: BASE_DIR, stdio: 'pipe', timeout: 30000 });
    log('Pushed to GitHub');
  } catch (_err) {
    log('WARNING: Push failed — run: cd ~/.mindlore && git push -u origin main');
  }

  console.log(`\n  Done! Your knowledge is backed up at: https://github.com/${repoFull}`);
  log('Session-end hook will auto-sync on every session close.');
}

export function createPreEvictionTag(mindloreDir: string): string {
  const date = new Date().toISOString().slice(0, 10);
  let tag = `pre-eviction-${date}`;

  try {
    const existing = execSync(`git tag -l "${tag}*"`, {
      cwd: mindloreDir, encoding: 'utf8',
    }).trim();

    if (existing.includes(tag)) {
      const count = existing.split('\n').length;
      tag = `${tag}-${count}`;
    }

    const status = execSync('git status --porcelain', { cwd: mindloreDir, encoding: 'utf8' }).trim();
    if (status) {
      execSync('git add -A && git commit -m "pre-eviction snapshot"', { cwd: mindloreDir });
    }

    execSync(`git tag ${tag}`, { cwd: mindloreDir });
    return tag;
  } catch (_err) {
    return tag;
  }
}

function main(): void {
  const args = process.argv.slice(2);
  const subcommand = args[0];

  console.log('\n  Mindlore Backup\n');

  switch (subcommand) {
    case 'init':
      backupInit();
      break;
    case 'status':
      backupStatus();
      break;
    case 'remote':
      if (!args[1]) {
        console.error('  Usage: mindlore backup remote <url>');
        process.exit(1);
      }
      backupRemote(args[1]);
      break;
    case 'now':
      backupNow();
      break;
    case 'github':
      backupGithub();
      break;
    default:
      console.log('  Usage:');
      log('mindlore backup init         — Initialize backup');
      log('mindlore backup github       — Create private GitHub repo + auto-setup');
      log('mindlore backup status       — Show backup status');
      log('mindlore backup remote <url> — Set remote repository');
      log('mindlore backup now          — Commit + push now');
      break;
  }
}

main();
